version: "3"
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: DockerfileClient
    image: leeseunghoon99/react-map
    ports:
      - "80:3000"
  server:
    container_name: server
    build:
      context: .
      dockerfile: DockerfileServer
    image: leeseunghoon99/express-server
    ports:
      - "4000:4000"